# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: Mysite2
  # encoding: unicode
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432
 
production:
  adapter: postgresql
  encoding: unicode
  database: Mysite2
  username: root
  password: root
  pool: 5
  port: 5432
